### ISSUE TITLE
Some questions about the minimal example in your paper

### ISSUE THREAD

**Issue by Yongze-zzz** [DIR-LAB/VCSR#1] opened 2023-03-18 02:43 UTC
Dear authors , thanks for sharing your code. I have run your code successfully. But I still have some questions about your example figure 5:VCSR storage format in your paper.
![image](https://user-images.githubusercontent.com/70116723/226079299-c9b81a62-86ca-4703-81d2-fa3b9354ba45.png)
As we can see ,the length of your underlying edge array in figure 5 is 16. But I use the example graph as the code input graph. The length of underlying array is 48,and it seems like there are some redundant edges in it.
![image](https://user-images.githubusercontent.com/70116723/226079445-0c2611ba-da78-49c6-92d2-87ab5ebb2ada.png)
The edges_[i] = 3 has been stored third times.

**Comment by biqar** [comment] 2023-03-18 05:13
Dear @Yongze-zzz, Thanks for trying our code. `Figure 5` is just a toy example showing the overall architecture of VCSR. We can help you better understand your test case. Can you please share the dataset (base graph and dynamic graph insertions) you used in your test case?

**Comment by Yongze-zzz** [comment] 2023-03-18 05:22
My base graph is same as graph in the figure 5.
![image](https://user-images.githubusercontent.com/70116723/226086415-cde851c8-0a27-41bc-9790-25790cb4c777.png)
The whole graph will be loaded as the base graph and I did not try dynamic scene.
I think the reason why those reduant edges occured is the read_index less that new_position[curr vertex].
So the edges_[curr vertex] do not be reseted.

**Comment by biqar** [comment] 2023-03-18 06:11
Thanks for your explanation. I understand the issue now. After building the graph (using the example graph as the base graph and no further dynamic insertion), here is the vertex and edge array (you can similarly print these arrays by using the utility functions `print_vertices()` and `print_edges()` implemented in the `graph.h`):

Vertex Array: (0)|0,2| (1)|8,4| (2)|22,1| (3)|27,2| (4)|35,1| (5)|40,2| 
Edge Array: 1 3 0 3 4 5 5 0 0 3 4 5 0 0 0 0 0 0 0 0 0 0 5 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 2 0 0 0 0 0 0 
Edge Array (marked): `1 3` 0 3 4 5 5 0 `0 3 4 5` 0 0 0 0 0 0 0 0 0 0 `5` 0 0 0 0 `0 1` 0 0 0 0 0 0 `1` 0 0 0 0 `1 2` 0 0 0 0 0 0 

The vertex array is printed in this format: `(vertex-id)|starting-index-in-edge-array, degree|`. The edge array (marked) shows each vertex's adjacency list (follow the `starting-index-in-edge-array` and `degree` of the corresponding vertex). The other edge-array entries (unmarked region) are empty cells that will be used in future insertions. You are considering these empty cells as redundant edges. We did not reset these empty cells in the edge array because valid edges can be identified by the vertex metadata (starting index and the degree).

The length of the edge array is 48; why?
Please check the `compute_capacity()` function implemented in the `graph.h`.

I hope this will help clear up your reported issue. Feel free to let me know if you have any further questions.

**Comment by Yongze-zzz** [comment] 2023-03-24 06:34
Tks!
I try to reproduce the experiment in your paper, by the way , does the insert function support cilk_for g.insert(src,dst,value) ?

**Comment by biqar** [comment] 2023-03-24 12:41
The current version of VCSR only supports single-thread insertion and concurrent graph analysis.

**Comment by biqar** [comment] 2023-03-24 12:43
@Yongze-zzz As the problem is resolved, I am closing this issue now. Feel free to create another issue if you face any further problems.

**Closed as completed by biqar** 2023-03-24 12:43 UTC
